import type { DatabaseSchema, DatabaseTable, DatabaseField } from '@forge/compiler';
import { mapFieldTypeToPrisma } from './mapper.js';

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generatePrisma(schema: DatabaseSchema): GeneratedFile[] {
  const content = renderPrismaSchema(schema);
  return [
    {
      path: 'prisma/schema.prisma',
      content
    }
  ];
}

function renderPrismaSchema(schema: DatabaseSchema): string {
  const models = schema.tables.map(table => renderTable(table)).join('\n\n');

  return `// This file is auto-generated by Forge
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models}
`;
}

function renderTable(table: DatabaseTable): string {
  const fieldLines = table.fields.map(field => renderField(field)).join('\n');
  return `model ${table.name} {
${fieldLines}
}`;
}

function renderField(field: DatabaseField): string {
  const type = mapFieldTypeToPrisma(field.type);
  const nullable = field.isNullable ? '?' : '';
  const modifiers: string[] = [];

  if (field.isPrimary) {
    modifiers.push('@id');
  }

  if (field.isUnique && !field.isPrimary) {
    modifiers.push('@unique');
  }

  const modifiersStr = modifiers.length > 0 ? ` ${modifiers.join(' ')}` : '';

  return `  ${field.name} ${type}${nullable}${modifiersStr}`;
}
