import type { DatabaseSchema, DatabaseTable, DatabaseField } from '@forge/compiler';
import { mapFieldTypeToPrisma } from './mapper.js';

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generatePrisma(schema: DatabaseSchema): GeneratedFile[] {
  const content = renderPrismaSchema(schema);
  return [
    {
      path: 'prisma/schema.prisma',
      content
    }
  ];
}

function renderPrismaSchema(schema: DatabaseSchema): string {
  const enums = (schema.enums ?? []).map(item => renderEnum(item)).join('\n\n');
  const relations = analyzeRelations(schema);
  const models = schema.tables.map(table => renderTable(table, relations)).join('\n\n');
  const body = [enums, models].filter(Boolean).join('\n\n');

  return `// This file is auto-generated by Forge
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${body}
`;
}

function renderEnum(enumModel: DatabaseSchema['enums'][number]): string {
  const values = enumModel.values.map(value => `  ${value}`).join('\n');
  return `enum ${enumModel.name} {\n${values}\n}`;
}

function renderTable(table: DatabaseTable, relations: RelationAnalysis): string {
  const fieldLines = table.fields.map(field => renderField(field, table, relations)).join('\n');
  const generatedRelationLines = relations.generatedBackRelations
    .get(table.name)
    ?.map(relation => `  ${relation.fieldName} ${relation.sourceModel}[] @relation("${relation.relationName}")`)
    .join('\n');
  const indexLines = (table.indexes ?? []).map(field => `  @@index([${field}])`).join('\n');
  const body = [fieldLines, generatedRelationLines, indexLines].filter(Boolean).join('\n');
  return `model ${table.name} {
${body}
}`;
}

function renderField(field: DatabaseField, table: DatabaseTable, relations: RelationAnalysis): string {
  const baseType = field.type === 'enum' || field.type === 'relation'
    ? field.typeName ?? mapFieldTypeToPrisma(field.type)
    : mapFieldTypeToPrisma(field.type);
  const type = field.isArray ? `${baseType}[]` : baseType;
  const nullable = field.isNullable && !field.isArray ? '?' : '';
  const modifiers: string[] = [];

  if (field.isPrimary) {
    modifiers.push('@id');
  }

  if (field.isUnique && !field.isPrimary) {
    modifiers.push('@unique');
  }

  if (field.default) {
    modifiers.push(`@default(${renderDefault(field.default)})`);
  }

  const relationName = field.type === 'relation' ? relations.fieldRelationNames.get(fieldKey(table.name, field.name)) : undefined;
  if (field.relation?.fields?.length && field.relation.references?.length) {
    const nameArgument = relationName ? `"${relationName}", ` : '';
    modifiers.push(`@relation(${nameArgument}fields: [${field.relation.fields.join(', ')}], references: [${field.relation.references.join(', ')}])`);
  } else if (relationName) {
    modifiers.push(`@relation("${relationName}")`);
  }

  const modifiersStr = modifiers.length > 0 ? ` ${modifiers.join(' ')}` : '';

  return `  ${field.name} ${type}${nullable}${modifiersStr}`;
}

interface RelationAnalysis {
  fieldRelationNames: Map<string, string>;
  generatedBackRelations: Map<string, GeneratedBackRelation[]>;
}

interface GeneratedBackRelation {
  sourceModel: string;
  fieldName: string;
  relationName: string;
}

function analyzeRelations(schema: DatabaseSchema): RelationAnalysis {
  const fieldRelationNames = new Map<string, string>();
  const generatedBackRelations = new Map<string, GeneratedBackRelation[]>();

  for (const table of schema.tables) {
    for (const field of table.fields.filter(isOwningRelation)) {
      const targetModel = field.relation.targetModel;
      const relationName = `${table.name}_${field.name}`;
      fieldRelationNames.set(fieldKey(table.name, field.name), relationName);

      const declaredBackRelation = schema.tables
        .find(candidate => candidate.name === targetModel)
        ?.fields
        .find(candidate =>
          candidate.type === 'relation'
          && candidate.typeName === table.name
          && !candidate.relation?.fields?.length
        );

      if (declaredBackRelation) {
        fieldRelationNames.set(fieldKey(targetModel, declaredBackRelation.name), relationName);
        continue;
      }

      const generated = generatedBackRelations.get(targetModel) ?? [];
      generated.push({
        sourceModel: table.name,
        fieldName: uniqueBackRelationName(pluralize(table.name), schema.tables.find(candidate => candidate.name === targetModel)?.fields ?? [], generated),
        relationName
      });
      generatedBackRelations.set(targetModel, generated);
    }
  }

  return { fieldRelationNames, generatedBackRelations };
}

function isOwningRelation(field: DatabaseField): field is DatabaseField & { relation: { targetModel: string; fields: string[]; references: string[] } } {
  return field.type === 'relation'
    && Boolean(field.relation?.targetModel)
    && Boolean(field.relation?.fields?.length)
    && Boolean(field.relation?.references?.length);
}

function fieldKey(modelName: string, fieldName: string): string {
  return `${modelName}.${fieldName}`;
}

function pluralize(name: string): string {
  const value = name.charAt(0).toLowerCase() + name.slice(1);
  return value.endsWith('s') ? value : `${value}s`;
}

function uniqueBackRelationName(baseName: string, declaredFields: DatabaseField[], generatedFields: GeneratedBackRelation[]): string {
  const used = new Set([
    ...declaredFields.map(field => field.name),
    ...generatedFields.map(field => field.fieldName)
  ]);
  if (!used.has(baseName)) {
    return baseName;
  }

  let index = 2;
  while (used.has(`${baseName}${index}`)) {
    index++;
  }
  return `${baseName}${index}`;
}

function renderDefault(raw: string): string {
  if (raw === 'now()' || raw === 'uuid()' || raw.startsWith('"') || raw === 'true' || raw === 'false') {
    return raw;
  }
  if (!Number.isNaN(Number(raw))) {
    return raw;
  }
  return raw;
}
